version: '3.3'

services:
  android:
    build: .
    ports:
      - 8081:8081
    volumes:
      - ./__tests__:/usr/src/app/__tests__
      - ./android:/usr/src/app/android
      - ./app:/usr/src/app/app